server:
  port: ${PORT:8502} #写成这样，在vm options 添加-DPORT=8002，就能开启不同端口的多个程序


#注册服务
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      #defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
      #defaultZone: http://localhost:7000/eureka  #注册服务的地址
       defaultZone: http://localhost:7000/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    #ip-address: ${IP_ADDRESS:127.0.0.1} #手动写上，eureka就不用解析主机名，我们给他解析好了
    instance-id: ${spring.application.name}:${server.port} #指定实例id,别名

# eureka的info页面配置，build.version以$开头结尾，必须再parent工程中配置build
info:
  app.name: manager-redis-8502
  company.name: xx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS

spring:
  redis:
      host: 192.168.38.128
      password:
      port: 6379
      timeout: 10000 # 连接超时时间（毫秒）
      database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
          max-idle: 8 # 连接池中的最大空闲连接默认 8
          min-idle: 0 # 连接池中的最小空闲连接默认 0
  boot:
    admin:
      client:
        url: http://localhost:8085
  zipkin:
    base-url: http://localhost:3344
  application:
    name: manager-redis-8502           #很重要，对外暴露服务的名字。入住eureka的名字
